site_name: Documentación
site_description: An informative description
docs_dir: docs
plugins:
  - techdocs-core
nav:
  - Getting Started: index.md
  - Conceptos: Conceptos.md
  - Integracion: Integracion.md
  - Complementos: Complementos.md
  - Arquitectura: Arquitectura.md
